language: generic
sudo: required
services:
  - docker

after_success:
  - docker build -t eugene2238/dashboard_update-widgets ./apps/dashboard_update-widgets
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push eugene2238/dashboard_update-widgets
